name = "tunel-admin-api"
main = "dist/index.js"
compatibility_date = "2025-07-07"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm install && npm run build"

[vars]
NODE_ENV = "production"
ADMIN_EMAIL = "admin@tunel.com"
ADMIN_PASSWORD = "admin123"
JWT_SECRET = "tunel-cloudflare-secret-2024"

# Custom domain settings (after domain purchase)
# routes = [
#   { pattern = "api.tunel.com/*", zone_name = "tunel.com" }
# ]

[[env.production]]
name = "tunel-admin-api"
vars = { NODE_ENV = "production" }

[[env.development]]
name = "tunel-admin-api-dev"
vars = { NODE_ENV = "development" }