name = "tunel-admin"
main = "dist/index.js"
compatibility_date = "2025-07-07"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[vars]
NODE_ENV = "production"
ADMIN_EMAIL = "admin@tunel.com"
ADMIN_PASSWORD = "admin123"
JWT_SECRET = "tunel-cloudflare-secret-2024"
